config/routes.rb
Rails.application.routes.draw do
  get "tos", to: "welcome#tos", as: "tos"
  get "policy", to: "welcome#policy", as: "policy"

  authenticated :user do
    root to: "tenhou_accounts#index"
  end
  root to: "welcome#index", as: "home"

  devise_for :users, skip: %i[sessions registrations]
  devise_scope :user do
    get "signup", to: "devise/registrations#new"
    post "signup", to: "devise/registrations#create"
    get "login", to: "devise/sessions#new"
    # deviseが内部で使用するヘルパーメソッド
    get "login", to: "devise/sessions#new", as: "new_user_session"
    post "login", to: "devise/sessions#create"
    delete "logout", to: "devise/sessions#destroy"
    delete "retirement", to: "devise/registrations#destroy"
    get "my_page", to: "devise/registrations#edit", as: :edit_user_registration
    patch "my_page", to: "devise/registrations#update", as: nil
    put "my_page", to: "devise/registrations#update", as: :update_user_registration
  end

  resources :tenhou_accounts
  resources :teams, only: %i[new edit create update]
  get "teams/join", to: "teams/joins#new", as: "new_team_join"
  post "teams/join", to: "teams/joins#create"
  delete "teams/join", to: "teams/joins#destroy"
  get "teams/invite", to: "teams/invites#new"
  post "teams/invite", to: "teams/invites#create"
  get "teams/:id/logs", to: "teams/logs#index", as: "team_logs"
end

app/models/tenhou_account.rb
class TenhouAccount < ApplicationRecord
  belongs_to :team
  validates :name,
    presence: true,
    length: { maximum: 8 },
    uniqueness: { scope: :team_id }
  validate :correct_tenhou_account

  def correct_tenhou_account
    if [" ", "　"].any? { |i| name.include?(i) }
      errors.add(:name, "に使用できない文字が含まれています")
    end
  end
end

app/controllers/tenhou_accounts_controller.rb
class TenhouAccountsController < ApplicationController
  include TenhouAccountsHelper
  include LogsHelper
  before_action :authenticate_user!
  before_action :set_tenhou_account, only: %i[show edit update destroy]
  before_action :authenciate_team_member, only: %i[show edit update destroy]

  def index
    @tenhou_accounts = current_user.team&.tenhou_accounts
  end

  def show
    hash = three_and_four_games_of(@tenhou_account)
    @three_games = hash[:three_games]
    @four_games = hash[:four_games]
    @my_one_game_objects = OneGame.my_one_game_objects_of(@tenhou_account)

    @one_month_games = OneMonthGames.make_one_month_games_objects(@my_one_game_objects)

    # 全期間の得点が入った配列
    @four_games_scores = scores(@four_games, @tenhou_account.name)
    @three_games_scores = scores(@three_games, @tenhou_account.name)

    # 全期間の順位が入った配列
    @four_games_rankings = rankings(@four_games, @tenhou_account.name)
    @three_games_rankings = rankings(@three_games, @tenhou_account.name)
  end

  def new
    @tenhou_account = TenhouAccount.new
  end

  def edit
  end

  def create
    @tenhou_account = TenhouAccount.new(tenhou_account_params)
    @tenhou_account.team = current_user.team

    if @tenhou_account.save
      redirect_to root_path, notice: "チームにメンバーを追加しました。"
    else
      render :new
    end
  end

  def update
    if @tenhou_account.update(tenhou_account_params)
      redirect_to edit_team_path(@tenhou_account.team), notice: "天鳳アカウントを変更しました。"
    else
      render :edit
    end
  end

  def destroy
    @tenhou_account.destroy
    redirect_to root_path, notice: "メンバーを削除しました。"
  end

  private
    def set_tenhou_account
      @tenhou_account = TenhouAccount.find(params[:id])
    end

    def tenhou_account_params
      params.require(:tenhou_account).permit(:name)
    end

    def authenciate_team_member
      if @tenhou_account.team != current_user.team
        redirect_to root_path, notice: "権限がありません"
      end
    end
end

app/helpers/tenhou_accounts_helper.rb
module TenhouAccountsHelper
  def three_and_four_games_of(tenhou_account)
    my_one_game_objects = OneGame.my_one_game_objects_of(tenhou_account)
    # この配列に全期間の3人打ちと4人打ちのgame_objectが格納されている
    three_games = []
    four_games = []
    my_one_game_objects.each do |my_one_game_object|
      if my_one_game_object.type == 3
        three_games << my_one_game_object
      else
        four_games << my_one_game_object
      end
    end
    { three_games: three_games, four_games: four_games }
  end
end

app/views/tenhou_accounts/edit.html.slim
- if @tenhou_account.errors.any?
  .alert.alert-danger
    - @tenhou_account.errors.full_messages.each do |msg|
     li.mb-0 = msg

.form
  h2.page-title
    | アカウント名変更
  = form_with model: @tenhou_account, local: true do |f|
    .form-group
      = f.label :name
      = f.text_field :name, autofocus: true, class: "form-control"
    .btn-register
      = f.submit "保存", class: "btn btn-success"

  .links.row
    .col-lg-2.offset-lg-3.link-wrapper
      = link_to "削除", tenhou_account_path(@tenhou_account), method: :delete, data: { confirm: "本当に削除してよろしいですか？" }
    .col-lg-2.link-wrapper
      = link_to "ホーム", root_path
    .col-lg-3.link-wrapper
      = link_to "チーム設定", edit_team_path(current_user.team)

app/views/tenhou_accounts/index.html.slim
= javascript_pack_tag "user"

- if current_user.team.present?
    - if @tenhou_accounts.present?
      h2.page-title
        | #{current_user.team.name}の成績
      #table
        .form-check
          input#all-term type="checkbox" v-model="changeAll" class="form-check-input"
          label for="all-term" class="form-check-label"
            | 全期間
        .d-flex.term
          p.first 期間を選択
          input type="date" v-model="changeStart"
          p 〜
          input type="date" v-model="changeEnd"

        table.table.table-hover
          thead
            tr
              th
              th
              th class="text-right" 4人打ち
              th
              th
              th class="text-right" 3人打ち
              th
            tr
              th scope="col" ユーザー
              th class="text-right" scope="col" 得点
              th class="text-right" scope="col" 平均順位
              th class="text-right" scope="col" 試合数
              th class="text-right" scope="col" 得点
              th class="text-right" scope="col" 平均順位
              th class="text-right" scope="col" 試合数
          tbody
          - @tenhou_accounts.each do |tenhou_account|
            - hash = three_and_four_games_of(tenhou_account)
            tr is="user" tenhou-name="#{tenhou_account.name}" three-games-string="#{hash[:three_games].to_json}" four-games-string="#{hash[:four_games].to_json}" url="#{tenhou_account_path(tenhou_account)}" v-bind:term="term"

      = link_to "ログを確認する", team_logs_path(current_user.team), class: "btn btn-primary"
      - if current_user.team.tenhou_accounts.count < 3
        = link_to "メンバーを追加", new_tenhou_account_path, class: "btn btn-primary ml-2"
    - else
      .alert.alert-warning.notice
        p
          | 天鳳アカウントが登録されていません。
        p
          | チームに天鳳アカウントを追加しましょう！
      .team-btns
        = link_to "メンバーを追加", new_tenhou_account_path, class: "btn btn-success"

- else
  .alert.alert-warning.notice
    p
      | どのチームにも所属していません。
    p
      | 新しくチームを作成するか、既存のチームに参加しましょう！
  .team-btns
    = link_to "チームを作成", new_team_path, class: "btn btn-success"
    = link_to "チームへ参加", new_team_join_path, class: "btn btn-success"

app/views/tenhou_accounts/new.html.slim
- if @tenhou_account.errors.any?
  .alert.alert-danger
    - @tenhou_account.errors.full_messages.each do |msg|
     li.mb-0 = msg

.form
  h2.page-title
    | メンバーを追加
  = form_with model: @tenhou_account, local: true do |f|
    .form-group
      = f.label :name
      = f.text_field :name, class: "form-control"
    .btn-register
      = f.submit "追加", class: "btn btn-success"
.links.row
    .col-lg-3.offset-lg-3.link-wrapper
      = link_to "チーム設定", edit_team_path(current_user.team)
    .col-lg-2.link-wrapper
      = link_to "ホーム", root_path

app/views/tenhou_accounts/show.html.slim
= javascript_pack_tag "result"

h2 = @tenhou_account.name
.main-box
  .right
    .score.score-right
      h3.mr-3
        | 総合成績
      p
        | 対戦数 #{@my_one_game_objects.count}
      p
        | 合計得点 #{(@four_games_scores + @three_games_scores).sum}
    - unless @four_games_scores.present?
      p
        | 4人打ちの対戦記録はありません
    - else
      .card.text-center.mb-3
        .card-header
          | 4人打ち
        .card-body
          .row
            .col-sm-4
              .card
                p.card-text.card-label
                  | 合計得点
                p.card-text.card-result
                  = @four_games_scores.sum
            .col-sm-4
              .card
                p.card-text.card-label
                  | 平均順位
                p.card-text.card-result
                  = (@four_games_rankings.sum(0.0) / @four_games_rankings.count).round(2)
            .col-sm-4
              .card
                p.card-text.card-label
                  | 対戦数
                p.card-text.card-result
                  = @four_games_scores.count

    - unless @three_games_scores.present?
      p
        | 3人打ちの対戦記録はありません。
    - else
      .card.text-center.mb-3.user-score
        .card-header
          | 3人打ち
        .card-body
          .row
            .col-sm-4
              .card
                p.card-text.card-label
                  | 合計得点
                p.card-text.card-result
                  = @three_games_scores.sum
            .col-sm-4
              .card
                p.card-text.card-label
                  | 平均順位
                p.card-text.card-result
                  = (@three_games_rankings.sum(0.0) / @three_games_rankings.count).round(2)
            .col-sm-4
              .card
                p.card-text.card-label
                  | 対戦数
                p.card-text.card-result
                  = @three_games_scores.count
  .left
    h3
      | 任意の期間の成績
    #results
      result(tenhou-name="#{@tenhou_account.name}"
        three-games-string="#{@three_games.to_json}"
        four-games-string="#{@four_games.to_json}"
      )

h3
  | 月別の成績
- @one_month_games.each do |game|
    - four_games_scores = scores(game.four_games, @tenhou_account.name)
    - four_games_rankings = rankings(game.four_games, @tenhou_account.name)
    - three_games_scores = scores(game.three_games, @tenhou_account.name)
    - three_games_rankings = rankings(game.three_games, @tenhou_account.name)
    .card.mb-3
      .card-header
        p = game.name
      .card-body
        - if four_games_scores.empty?
          p
            | 4人打ちの記録はありません
        - else
          p
            | 4人打ち | 合計得点 #{four_games_scores.sum}  | 平均順位 #{(four_games_rankings.sum(0.0) / four_games_rankings.count).round(2)} | 対戦数 #{four_games_scores.count}
        - if three_games_scores.empty?
          p
            | 3人打ちの記録はありません
        - else
          p
            | 3人打ち | 合計得点 #{three_games_scores.sum}  | 平均順位 #{(three_games_rankings.sum(0.0) / three_games_rankings.count).round(2)} | 対戦数 #{three_games_scores.count}