config/routes.rb
Rails.application.routes.draw do
  get "tos", to: "welcome#tos", as: "tos"
  get "policy", to: "welcome#policy", as: "policy"

  authenticated :user do
    root to: "tenhou_accounts#index"
  end
  root to: "welcome#index", as: "home"

  devise_for :users, skip: %i[sessions registrations]
  devise_scope :user do
    get "signup", to: "devise/registrations#new"
    post "signup", to: "devise/registrations#create"
    get "login", to: "devise/sessions#new"
    # deviseが内部で使用するヘルパーメソッド
    get "login", to: "devise/sessions#new", as: "new_user_session"
    post "login", to: "devise/sessions#create"
    delete "logout", to: "devise/sessions#destroy"
    delete "retirement", to: "devise/registrations#destroy"
    get "my_page", to: "devise/registrations#edit", as: :edit_user_registration
    patch "my_page", to: "devise/registrations#update", as: nil
    put "my_page", to: "devise/registrations#update", as: :update_user_registration
  end

  resources :tenhou_accounts
  resources :teams, only: %i[new edit create update]
  get "teams/join", to: "teams/joins#new", as: "new_team_join"
  post "teams/join", to: "teams/joins#create"
  delete "teams/join", to: "teams/joins#destroy"
  get "teams/invite", to: "teams/invites#new"
  post "teams/invite", to: "teams/invites#create"
  get "teams/:id/logs", to: "teams/logs#index", as: "team_logs"
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | 天の個室
    meta name="viewport" content="width=device-width, initial-scale=1"
    meta name="description" content="天の個室は、天鳳個室の成績を自動でダウンロード・計算します。成績を手動で入力する必要はもうありません。"
    = csrf_meta_tags
    = csp_meta_tag
    = javascript_pack_tag "application"
    = favicon_pack_tag "favicon.ico"
    = stylesheet_pack_tag "application"
  body
    header
      .header-wrapper
        = link_to "天の個室", root_path, class: "app-name"
        .header-right
          - if user_signed_in?
            = link_to "個人設定", edit_user_registration_path, class: "btn btn-success mobile-btn first-btn"
            - if current_user.team.present?
              = link_to "チーム設定", edit_team_path(current_user.team), class: "btn btn-success mobile-btn last-btn"
          - else
            = link_to "アカウント作成", signup_path, class: "btn btn-success mobile-btn first-btn"
            = link_to "ログイン", login_path, class: "btn btn-success mobile-btn last-btn"
    .container
      - if flash.notice
        .alert.alert-success.mt-3 = flash.notice
      - if flash.alert
        .alert.alert-warning.mt-3 = flash.alert
      = yield
    footer.bg-dark
      p.pt-3
        = link_to "利用規約", tos_path, class: "mr-2"
        = link_to "プライバシーポリシー", policy_path
      p
        | &copy;2020 ten-no-koshitu All rights reserved.